### ISSUE TITLE
[Question] What is happening when a single job in a batch fails ?

### ISSUE THREAD

**Issue by smknstd** [atymic/laravel-bulk-sqs-queue#3]
> That about it. The rest of the queue functions the exact same as normal :)

It would be great if readme would mention explicitly the behavior of a batch that includes a failure. Thanx !

**Comment by atymic** [comment]
Feel free to test and PR to the docs :)

**Comment by atymic** [comment]
I'd imagine it's the exact same as standard laravel since the only difference is batching the dispatches to amazon.

**Comment by smknstd** [comment]
Just saw this tweet, but I am not sure how it is related ... https://twitter.com/matthieunapoli/status/1463282893623545861

I'll try to PR if I find something :)

**Comment by smknstd** [comment]
I think you're right and it now seems obvious to me too. Batch is just a way to transmit jobs to sqs. Once received they are handled as separate messages, and there is no way to know they have come from a batch or not. There is no relation between messages (even if failing or something). 

When I do:

```
\Queue::bulk([
	new \App\Jobs\Foo,
	new \App\Jobs\Foo,
	new \App\Jobs\Bar, (failing)
	new \App\Jobs\Foo,
],'','default');
```
I see this in aws dashboard:

![Screenshot 2021-11-26 at 21-22-02 Amazon SQS](https://user-images.githubusercontent.com/2412608/143645535-86e97027-c930-49a2-b450-44936713f0a2.png)

It is the same number as with default laravel sqs queue (without your package). I don't know where I could monitor incoming requests in aws, but it should be lesser though.
