### ISSUE TITLE
Bulk SQS Queue with Laravel Vapor

### ISSUE THREAD

**Issue by ryanldy** [atymic/laravel-bulk-sqs-queue#8]
Hi @atymic. 

Thanks for this package that cuts the cost of SQS up to 10x. Do you have an idea how to implement this with [Laravel Vapor](https://vapor.laravel.com/)?

**Comment by atymic** [comment]
Hey Ryan,

We're on vapor, hence the reason for this package (having to use SQS for queues).
It works perfectly with vapor, are you having any issues?

**Comment by ryanldy** [comment]
Thanks for the quick reply! 

Since vapor uses `sqs` queue connection by default, how can I implement the new connection `sqs-bulk` and running `php artisan queue:work sqs-bulk --queue=default` in vapor?

**Comment by atymic** [comment]
You don't run `queue:work` in vapor, AWS handles that for you (it invokes your lambda with the queued jobs automatically outside of having to run any commands).

**Comment by ryanldy** [comment]
To summarize how to use the package for Vapor:

I just need to create a connection `sqs-bulk`,
```
'connections' => [
        'sqs-bulk' => [
            'driver'       => 'sqs-bulk',
            'key'          => env('AWS_ACCESS_KEY_ID'),
            'secret'       => env('AWS_SECRET_ACCESS_KEY'),
            'prefix'       => env('SQS_PREFIX', 'https://sqs.us-east-1.amazonaws.com/your-account-id'),
            'queue'        => env('SQS_QUEUE', 'default'),
            'suffix'       => env('SQS_SUFFIX'),
            'region'       => env('AWS_DEFAULT_REGION', 'us-east-1'),
            'after_commit' => false,
            'concurrency'  => 5, // Set the request concurrency, defaults to 5
        ],
]
```

and then skip the part `queue:work` since AWS will automatically handles this?

**Comment by atymic** [comment]
That's correct. We're running in prod on vapor with concurrency 10, no issues :)
Vapor will handle all the execution using the standard SQS driver :)

**Comment by ryanldy** [comment]
Got it! Thanks! Will try to implement this and close the issue.
